version: "3"

services:
  database:
    container_name: "test_db"
    image: postgres:15
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rpass
      - POSTGRES_DB=fishing_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: "test_server"
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "8088:8088"
    depends_on:
      - database

volumes:
  db-data: