shutdownTimeout: 5s

server:
  port: 8088
  writeTimeout: 10s
  readTimeout: 10s
  idleTimeout: 10s

dataBase:
  username: 'root'
  password: 'rpass'
  address: 'localhost:5432'
  dBName: 'fishing_db'
  params: '?pool_max_conns=10&pool_max_conn_lifetime=3m&prefer_simple_protocol=true'
  maxConnLifetime: 3m
  maxConnIdleTime: 3s
  maxOpenCons: 10
  maxIdleCons: 10